//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportGenerator {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class App : global::System.Configuration.ApplicationSettingsBase {
        
        private static App defaultInstance = ((App)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new App())));
        
        public static App Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"_ym_uid=1459544264488082873; _ym_isad=2; flt.rgn=77,78,66; flt.indstr=cT,sS,cU,cP,sT,sI,sF,cU4; __utmt_t=1; ddmc=1; __utma=96715016.1392010813.1459544264.1459586412.1459596428.4; __utmb=96715016.3.9.1459596857847; __utmc=96715016; __utmz=96715016.1459544264.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utmv=96715016.|1=auth=%40free!free=1; mutoken=H8FD-W3GT30xMwsVZFfNOUMdLEbM312-R3qDQdLAje0EqjkzKhuxxYKtj_8-jyF_oQpU35F1F62YiTZYEYJgi1UO6kmRdL-yOHYkAVVLEwg1; conv=e3c9f28986ac44e498d60db3a9230d97%2fFree%2c2016-04-01%2c2016-04-02%2fDemo%2c2016-04-02%2c2016-04-02")]
        public string Cookie {
            get {
                return ((string)(this["Cookie"]));
            }
            set {
                this["Cookie"] = value;
            }
        }
    }
}
